version: '3.8'
version: '3.8'
services:
  login:
    image: karthikganji/paytmlogin:latest
    ports:
      - "85:80"
    deploy:
      replicas: 6

  ppb:
    image: karthikganji/paytmppb:latest
    ports:
      - "86:80"
    deploy:
      replicas: 6

  wallet:
    image: karthikganji/paytmwallet:latest
    ports:
      - "87:80"
    deploy:
      replicas: 6

  nayaworld:
    image: karthikganji/paytmnayaworld:latest
    ports:
      - "88:80"
    deploy:
      replicas: 6
