version: '3.8'
version: '3.8'
services:
  login:
    image: karthikganji/paytmlogin:latest
    ports:
      - "81:80"
    deploy:
      replicas: 6

  dth:
    image: karthikganji/paytmppb:latest
    ports:
      - "82:80"
    deploy:
      replicas: 6

  movies:
    image: karthikganji/paytmwallet:latest
    ports:
      - "83:80"
    deploy:
      replicas: 6
