version: '3.8'
version: '3.8'
services:
  login:
    image: karthikganji/login:latest
    ports:
      - "81:80"
    deploy:
      replicas: 6

  dth:
    image: karthikganji/dth:latest
    ports:
      - "82:80"
    deploy:
      replicas: 6

  movies:
    image: karthikganji/movies:latest
    ports:
      - "83:80"
    deploy:
      replicas: 6

  ppb:
    image: karthikganji/movies:latest
    ports:
      - "84:80"
    deploy:
      replicas: 6


